### ISSUE TITLE
Exception help

### ISSUE THREAD

**Issue by JosephChenHub** [neuroailab/physics-models#1]
Hi, thanks for your contribution. Could you help me to debug this exception with the following error message? 

```
EN', 'extraction_OBJECTIVE_NAME': 'ExtractionObjective', 'extraction_LOAD_STEP': 2, 'extraction_NOTE': ''}

2022-07-27 05:37:53,963 [INFO] Found run with name: "pVGG_MLP-Collide-0-extraction-Collide"

2022-07-27 05:37:54,092 [ERROR] job exception: The following failures occurred while downloading one or more artifacts from exp01/physopt-example/mlruns/0/1d64e682bfb64bc7b5a85a64b5b3e056/artifacts: {'features/train_feat.pkl': "FileNotFoundError(2, 'No such file or directory')"}

  0%|                                                                                                                                                | 0/1 [00:01<?, ?trial/s, best loss=?]
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    run()
  File "/workspace/physopt-physics-benchmarking/physopt/opt.py", line 192, in run
    pipeline.run()
  File "/workspace/physopt-physics-benchmarking/physopt/opt.py", line 100, in run
    run_once(data_space)
  File "/workspace/physopt-physics-benchmarking/physopt/opt.py", line 90, in run_once
    run_inner(EXTRACTION_PHASE_NAME, readout_space)
  File "/workspace/physopt-physics-benchmarking/physopt/opt.py", line 74, in run_inner
    best = fmin(
  File "/usr/local/lib/python3.8/dist-packages/hyperopt/fmin.py", line 507, in fmin
    return trials.fmin(
  File "/usr/local/lib/python3.8/dist-packages/hyperopt/base.py", line 682, in fmin
    return fmin(
  File "/usr/local/lib/python3.8/dist-packages/hyperopt/fmin.py", line 553, in fmin
    rval.exhaust()
  File "/usr/local/lib/python3.8/dist-packages/hyperopt/fmin.py", line 356, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/usr/local/lib/python3.8/dist-packages/hyperopt/fmin.py", line 292, in run
    self.serial_evaluate()
  File "/usr/local/lib/python3.8/dist-packages/hyperopt/fmin.py", line 170, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/usr/local/lib/python3.8/dist-packages/hyperopt/base.py", line 907, in evaluate
    rval = self.fn(pyll_rval)
  File "/workspace/physopt-physics-benchmarking/physopt/objective/core.py", line 109, in __call__
    ret = self.call(args)
  File "/workspace/physopt-physics-benchmarking/physopt/objective/base.py", line 173, in call
    self.extract_feats(mode) 
  File "/workspace/physopt-physics-benchmarking/physopt/objective/base.py", line 177, in extract_feats
    feature_file = utils.get_feats_from_artifact_store(mode, self.tracking_uri, self.run_id, self.output_dir)
  File "/workspace/physopt-physics-benchmarking/physopt/objective/utils.py", line 144, in get_feats_from_artifact_store
    feat_file = download_from_artifact_store(artifact_path, tracking_uri, run_id, output_dir)
  File "/workspace/physopt-physics-benchmarking/physopt/objective/utils.py", line 128, in download_from_artifact_store
    client.download_artifacts(run_id, artifact_path, output_dir)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/tracking/client.py", line 1421, in download_artifacts
    return self._tracking_client.download_artifacts(run_id, path, dst_path)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/tracking/_tracking_service/client.py", line 401, in download_artifacts
    return self._get_artifact_repo(run_id).download_artifacts(path, dst_path)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/store/artifact/local_artifact_repo.py", line 74, in download_artifacts
    return super().download_artifacts(artifact_path, dst_path)
  File "/usr/local/lib/python3.8/dist-packages/mlflow/store/artifact/artifact_repo.py", line 263, in download_artifacts
    raise MlflowException(
mlflow.exceptions.MlflowException: The following failures occurred while downloading one or more artifacts from exp01/physopt-example/mlruns/0/1d64e682bfb64bc7b5a85a64b5b3e056/artifacts: {'features/train_feat.pkl': "FileNotFoundError(2, 'No such file or directory')"}
```

The running command is 
```
python3 run.py -C $PWD/configs/example.yaml -O $PWD/exp01
```
and about the `example.yaml`, I only change the path to the example data.

**Comment by JosephChenHub** [comment]
fixed it.  MLflow == 1.21.0 works!
